### PR TITLE
[Ready for Review] Fix parsing of docker ID to config.yaml

### LINKED ISSUE #42: Docker ID parsed as null in deploy.sh container mode
When the BinderHub is deployed, we're getting internal server errors due to the Docker ID not being parsed correctly to `config.yaml`.

Plan is to replace the python scripts `create_config.py` and `create_secret.py` with `sed` commands in `deploy.sh`. Then test the DOCKER_ORG `if` statement.

### Update

Changing python scripts for sed commands worked, but docker username is still being parsed as `null` to `config.yaml`.

Required:
```
config:
  BinderHub:
    use_registry: true
    image_prefix: dockerid/binder-dev-
```

Returned:
```
config:
  BinderHub:
    use_registry: true
    image_prefix: null/binder-dev-
```

### PR DESCRIPTION
**Pull request by sgibson91**
This PR makes sure that DOCKER_ORGANISATION is checked for null and set to an empty string when operating in container mode. This fixes the issue that docker-id was being parsed to config.yaml as null.

fixes #42

### CODE REVIEW

File: deploy.sh [hunk 1]
```diff
@@ -300,22 +320,24 @@ if [ -z "$DOCKER_ORGANISATION" ] ; then
...
 --version=$BINDERHUB_VERSION \
--f ./secret.yaml \
--f ./config.yaml | tee helm-upgrade.log
+-f ${DIR}/secret.yaml \
+-f ${DIR}/config.yaml | tee helm-upgrade.log
 
 # Print Binder IP address
+echo "--> Retrieving Binder IP"
 BINDER_IP=`kubectl --namespace=$HELM_BINDERHUB_NAME get svc binder | awk '{ print $4}' | tail -n 1`
+echo "Binder IP: ${BINDER_IP}"
```
Comment (tmbgreaves) [inline deploy.sh]:
```suggestion
echo "Binder IP: ${BINDER_IP}" | tee binder-ip.log
```
In the unlikely event it succeeds first time, ensure the miracle makes it into a log file :-)

Comment (sgibson91) [reply deploy.sh]: We do this on this line :) https://github.com/alan-turing-institute/binderhub-deploy/blob/90f7b62e6787667e3f2d80ee4d4f47e97bde8002/deploy.sh#L346

Comment (sgibson91) [reply deploy.sh]: However, this might not make it into the logs if the while loop is never triggered. So probably best to include this as a failsafe.
