### PR TITLE
Fix logs script to find hub pod name

### LINKED ISSUE #61: Line in logs.sh doesn't actually fetch the Hub pod name
So I noticed that in `logs.sh`, we have the following line to try to find the name of the hub pod so as to run `kubectl logs <hub-pod-name> -n <binderhub-name>`.

https://github.com/alan-turing-institute/binderhub-deploy/blob/fff5effdb9f56d177232ebfc803bb465ce95442a/logs.sh#L19

However, this line relies on the hub pod being somewhere near the bottom of the list output by `kubectl get pods -n <binderhub-name>`, and so won't actually pull the name of the hub pod once more pods are added to the cluster.

An example:

`kubectl get pods -n hub23`:
```
NAME                              READY   STATUS    RESTARTS   AGE
binder-7ccd9b5bb-59w5r            1/1     Running   0          2d1h
continuous-image-puller-9r8kd     1/1     Running   0          20d
continuous-image-puller-scplw     1/1     Running   0          20d
continuous-image-puller-wm7x7     1/1     Running   0          20d
hub-64474c9f4c-w2gfl              1/1     Running   0          20d
hub23-image-cleaner-cmv96         1/1     Running   0          2d4h
hub23-image-cleaner-npts4         1/1     Running   0          2d4h
hub23-image-cleaner-zn9lq         1/1     Running   0          2d4h
proxy-5fd7d5c599-tkhdt            1/1     Running   0          20d
user-placeholder-0                1/1     Running   0          20d
user-placeholder-1                1/1     Running   0          20d
user-placeholder-2                1/1     Running   0          20d
user-scheduler-68885f5688-lf24g   1/1     Running   23         20d
```

`kubectl get pods -n hub23 | awk '{ print $1}' `:
```
NAME
binder-7ccd9b5bb-59w5r
continuous-image-puller-9r8kd
continuous-image-puller-scplw
continuous-image-puller-wm7x7
hub-64474c9f4c-w2gfl
hub23-image-cleaner-cmv96
hub23-image-cleaner-npts4
hub23-image-cleaner-zn9lq
proxy-5fd7d5c599-tkhdt
user-placeholder-0
user-placeholder-1
user-placeholder-2
user-scheduler-68885f5688-lf24g
```

`OUTPUT=$(kubectl get pods -n hub23 | awk '{ print $1}' | tail -n 2)`:
```
user-placeholder-2
user-scheduler-68885f5688-lf24g
```

`echo ${OUTPUT[0]}`: gives no output.

This means that running `logs.sh` outputs nothing, rather than the logs! We should find a better way to get the hub pod name. Perhaps a grep command?

cc: @trallard @tmbgreaves

### PR DESCRIPTION
**Pull request by sgibson91**
Logs script was dependent on the position of the hub pod in the output of `kubectl get pods`. Fix this to use grep to always find the hub pod, no matter how many pods are running.

fixes #61 

cc @trallard or @tmbgreaves for a review 🙂

### CODE REVIEW

File: logs.sh [hunk 1]
```diff
@@ -16,9 +16,7 @@ az aks get-credentials -n $AKS_NAME -g $AKS_RESOURCE_GROUP
 echo "--> Fetching JupyterHub logs"
 
 # Get pod name of the JupyterHub
-OUTPUT=`kubectl -n ${BINDERHUB_NAME} get pod | awk '{ print $1}' | tail -n 2`
-OUTPUT=($OUTPUT)
-HUB_POD=${OUTPUT[0]}
+HUB_POD=`kubectl get pods -n hub23 -o=jsonpath='{.items[*].metadata.name}' | tr ' ' '\n' | grep "^hub-"`
```
Comment (sgibson91) [inline logs.sh]:
```suggestion
HUB_POD=`kubectl get pods -n ${BINDERHUB_NAME} -o=jsonpath='{.items[*].metadata.name}' | tr ' ' '\n' | grep "^hub-"`
```
